### PR TITLE
Minor bugs fixed and code improvement

### PR DESCRIPTION
**Pull request by lamhoangtung**
Hi. Thanks for you guys for the great works! 

Lately I been trying to apply GLNet for real world problem using you guys code and having little bugs here and there. After a month trying to resolve a bunch of them, I finally mange to get GLNet working for my binary segmentation problem.

This PR contain some minor bugs fix and improvement while I working with you guys code.

If this PR don't meet the quality for a merge. It's totally fine but please told me what can I do to complete my contribution to this repo :D

Regards and thanks, Linus ;)

### CODE REVIEW

**Comment by chenwydj** [comment]
This pull request **introduces 1 alert** when merging 46ebe82c334bd7eba4b4efa9439f1d10388c80b2 into 867d2a644b88fc9131d250d589129211279fd0b7 - [view on LGTM.com](https://lgtm.com/projects/g/TAMU-VITA/GLNet/rev/pr-218570fcd97601dbe3b80525d9ed328db9fb9c28)

**new alerts:**

* 1 for Unused import

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by chenwydj** [comment]
This pull request **fixes 5 alerts** when merging c9d6b4dc28d0c9f61b737b43d9bb019bfe5e0374 into 867d2a644b88fc9131d250d589129211279fd0b7 - [view on LGTM.com](https://lgtm.com/projects/g/TAMU-VITA/GLNet/rev/pr-2ba7c0123d7fc14f4e73d42cd8bca40032813a11)

**fixed alerts:**

* 4 for Unused import
* 1 for NotImplemented is not an Exception

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by chenwydj** [comment]
Hi Hoàng Tùng Lâm! Thank you very much for your interest and great effort! I will review your commit and get back to you soon!

**Comment by lamhoangtung** [comment]
Thanks @chenwydj ;)

**Comment by chenwydj** [comment]
This pull request **introduces 1 alert** and **fixes 5** when merging 0dc47fac116d760bda5e848fee44d69a133bce83 into 867d2a644b88fc9131d250d589129211279fd0b7 - [view on LGTM.com](https://lgtm.com/projects/g/TAMU-VITA/GLNet/rev/pr-7e86431ab24bcbacf2c0b0b00611894b27e9b372)

**new alerts:**

* 1 for Unused import

**fixed alerts:**

* 4 for Unused import
* 1 for NotImplemented is not an Exception

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by lamhoangtung** [comment]
Since everything from training script and pertained model was uploaded by the author. I will close this PR :P

**Pull request closed without merging**
